Create_MainPage
IrinaSKab/hotel pull request #1
Opened 2019-10-28 20:33 UTC by IrinaSKab

2019-10-28 22:36 UTC, Afelua requested changes

2019-10-28 22:36 UTC, Afelua commented on index.html
> +		<h1 class="title">гостиницы по лучшим ценам</h1>
Здесь еще должен быть логотип JCB

2019-10-28 22:36 UTC, Afelua commented on index.html
> +<body class="image">
По картинке - стоит еще добавить градиент через псевдоэлемент before. Параметры градиента:
<img width="283" alt="Screenshot 2019-10-29 at 01 19 22" src="https://user-images.githubusercontent.com/8777546/67722432-27fbfd00-f9ea-11e9-8025-8a6147debf83.png">
задаются через свойство background-image.

2019-10-28 22:36 UTC, Afelua commented on styles.css
> +.form__inputDate {
Над инпутами стоит поработать и задать параметры шрифта для текста внутри. Также есть страничка с элементами https://app.zeplin.io/project/5db5aab1b9175d22aaf317c6/screen/5db5b1fbb864471285cb766f, и на ней показано, как должен отображаться текст внутри инпута. У него стоит прописать padding слева.

2019-10-28 22:36 UTC, Afelua commented on styles.css
> +.form__inputDate {
Аналогично потребуется задать шрифты для select.

2019-10-28 22:36 UTC, Afelua commented on index.html
> +			<textarea placeholder="Направление, город, название отеля: например Париж, Милан" class="form__textarea"></textarea>
Здесь еще иконку поиска стоит сделать справа. Лучше всего через псевдоэлемент для родительского div, а задать саму картинку - через background-image.

2019-10-28 22:36 UTC, Afelua commented on index.html
> +
Также хотелось бы видеть блок "Добавить перелет".

2019-10-28 22:36 UTC, Afelua commented on index.html
> +		</form>
И текст под кнопкой)

2019-10-28 22:36 UTC, Afelua commented on styles.css
> +.form__button {
Пишем outline:none для всех input и button, чтобы не было страшной синей обводки

2019-10-28 22:36 UTC, Afelua commented on styles.css
> +	margin-top: 120px;
Сейчас блок с формой и блок с текстом не располагаются четко по центру, и их местоположение зависит от размера экрана пользователя. У меня, например, результат выглядит так:

<img width="1440" alt="Screenshot 2019-10-29 at 01 26 17" src="https://user-images.githubusercontent.com/8777546/67722767-1ff08d00-f9eb-11e9-8d20-56f0c3968ee0.png">

Чтобы такого не было и элементы располагались четко по центру, есть несколько способов - https://medium.com/@stasonmars/%D0%B2%D0%B5%D1%80%D1%82%D0%B8%D0%BA%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5-%D0%B8-%D0%B3%D0%BE%D1%80%D0%B8%D0%B7%D0%BE%D0%BD%D1%82%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5-%D1%86%D0%B5%D0%BD%D1%82%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B2%D1%81%D0%B5%D0%B3%D0%BE-%D0%B8-%D0%B2%D1%81%D1%8F-%D0%B2-css-flexbox-fafd369fc71f

2019-10-28 22:36 UTC, Afelua commented on styles.css
> +	width: 952px;
Сейчас инпуты уехали вправо относительно textarea:

<img width="1112" alt="Screenshot 2019-10-29 at 01 31 12" src="https://user-images.githubusercontent.com/8777546/67723030-cf2d6400-f9eb-11e9-815f-a0ac4c46b8ba.png">

Чтобы не писать margin-left для textarea, инпутов и всех последующих элементов (один и тот же), стоит добавить padding у .form, а все margin слева/справа его дочерних элементов обрать.

2019-10-28 22:36 UTC, Afelua commented on styles.css
> +	text-align: left;
text-align по умолчанию left, его нет смысла указывать дополнительно.

2019-10-28 22:36 UTC, Afelua commented on styles.css
> +	border-radius: 3px;
В идеале, вынеси все повторяющиеся стили в отдельный класс
```
.form__input {
	border-radius: 3px;
	border: solid 1px #35363c;
}
```

А все отличающиеся задать через модификатор:
```
.form_inputPerson {
	width: 105px;
	height: 50px;
}
```

Т.е. у одного элемента будет два класса form__input и form_inputPerson. Такое же провернуть для остальных инпутов)

2019-11-03 17:20 UTC, IrinaSKab commented on index.html
> +<body class="image">
при добавлении content:''; весь фон становится серым, в том числе и форма и инпуты не активны

2019-11-03 17:21 UTC, IrinaSKab commented on index.html
> +			<textarea placeholder="Направление, город, название отеля: например Париж, Милан" class="form__textarea"></textarea>
пробовала по-разному: у меня иконка не устанавливается справа в textarea

2019-11-03 17:22 UTC, IrinaSKab commented on index.html
> +
правильно ли, что добавлен чекбокс? не удается в одну строку сформировать его, самолет и текст

2019-11-03 17:27 UTC, IrinaSKab commented on styles.css
> +	width: 952px;
пробовала через padding у .form, но у меня в итоге сама форма увеличивается в размерах. Собственно и с margin не получается, поскольку расстояние между  инпутами неодинаковое

2019-11-03 17:27 UTC, IrinaSKab commented on styles.css
> +	border-radius: 3px;
этот комментарий отработаю чуть позже

2019-11-04 10:12 UTC, Afelua commented on index.html
> +<body class="image">
Тогда нужно еще поиграться с[ z-index](https://medium.com/nuances-of-programming/%D0%BE%D0%B1%D1%8A%D1%8F%D1%81%D0%BD%D1%8F%D0%B5%D0%BC-z-index-%D0%BA%D0%B0%D0%BA-%D0%BF%D0%BE%D0%B7%D0%B8%D1%86%D0%B8%D0%BE%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%8B-%D1%81-%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%D1%8E-css-e80bc85cf36c). Позволяет задать расположение элементов в 3-х мерном измерении. Здесь должно подойти значение -1 для псевдоэлемента.

2019-11-04 10:23 UTC, Afelua commented on index.html
> +			<textarea placeholder="Направление, город, название отеля: например Париж, Милан" class="form__textarea"></textarea>
http://htmlbook.ru/css/box-sizing

2019-11-17 22:12 UTC, Afelua requested changes

2019-11-17 22:12 UTC, Afelua commented on index.html
> +				<label class="nameInputDate"> Выберите дату вселения
Такого не должно быть. Синяя область должна вмещать весь элемент (календарь), а не только его часть. Иначе верстка считается непрофессиональной)
<img width="493" alt="Screenshot 2019-11-18 at 01 05 31" src="https://user-images.githubusercontent.com/8777546/69014864-a6234200-099f-11ea-93f2-6f82a98ae7a5.png">

2019-11-17 22:12 UTC, Afelua commented on calendar.css
> +	float: left;
float использовать нельзя, устаревшая конструкция (на заре 2010-х). Сейчас все выстраивание в 1 строку делаем через flex.

2019-11-17 22:12 UTC, Afelua commented on index.html
> +				<label class="nameInputDate"> Выберите дату вселения
По Pixel Perfect еще стоит поправить + добавить отступ между инпутом (снизу) и календарем.
<img width="457" alt="Screenshot 2019-11-18 at 01 10 56" src="https://user-images.githubusercontent.com/8777546/69014962-6577f880-09a0-11ea-8db0-b7c00efc1d9d.png">

2019-11-20 21:55 UTC, Afelua approved these changes

2019-11-21 20:14 UTC, merged